# Computer Science House
# Jekyll Global Configuration

title: Computer Science House
email: webmaster@csh.rit.edu
description: >
  Since 1976, Computer Science House has provided a revolutionary
  living and learning environment for its members. With unique facilities,
  emphasis on hands-on learning, and a strong social atmosphere,
  CSH helps its members grow as professionals and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csh.rit.edu" # the base hostname & protocol for your site
opcomm_twitter_username: OPCOMM
history_twitter_username: CSH_History
github_username:  ComputerScienceHouse